// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: server/mux/mux_error.proto

package mux

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error is the generic error returned from unary RPCs.
type MuxError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details []*anypb.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *MuxError) Reset() {
	*x = MuxError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_mux_mux_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MuxError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuxError) ProtoMessage() {}

func (x *MuxError) ProtoReflect() protoreflect.Message {
	mi := &file_server_mux_mux_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuxError.ProtoReflect.Descriptor instead.
func (*MuxError) Descriptor() ([]byte, []int) {
	return file_server_mux_mux_error_proto_rawDescGZIP(), []int{0}
}

func (x *MuxError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MuxError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MuxError) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_server_mux_mux_error_proto protoreflect.FileDescriptor

var file_server_mux_mux_error_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x75, 0x78, 0x2f, 0x6d, 0x75, 0x78,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x75,
	0x78, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x08,
	0x4d, 0x75, 0x78, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x2e, 0x77, 0x6f,
	0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x65, 0x69, 0x64, 0x61, 0x2f, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x6d, 0x75, 0x78, 0x3b, 0x6d,
	0x75, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_mux_mux_error_proto_rawDescOnce sync.Once
	file_server_mux_mux_error_proto_rawDescData = file_server_mux_mux_error_proto_rawDesc
)

func file_server_mux_mux_error_proto_rawDescGZIP() []byte {
	file_server_mux_mux_error_proto_rawDescOnce.Do(func() {
		file_server_mux_mux_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_mux_mux_error_proto_rawDescData)
	})
	return file_server_mux_mux_error_proto_rawDescData
}

var file_server_mux_mux_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_mux_mux_error_proto_goTypes = []interface{}{
	(*MuxError)(nil),  // 0: mux.MuxError
	(*anypb.Any)(nil), // 1: google.protobuf.Any
}
var file_server_mux_mux_error_proto_depIdxs = []int32{
	1, // 0: mux.MuxError.details:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_mux_mux_error_proto_init() }
func file_server_mux_mux_error_proto_init() {
	if File_server_mux_mux_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_mux_mux_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MuxError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_mux_mux_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_mux_mux_error_proto_goTypes,
		DependencyIndexes: file_server_mux_mux_error_proto_depIdxs,
		MessageInfos:      file_server_mux_mux_error_proto_msgTypes,
	}.Build()
	File_server_mux_mux_error_proto = out.File
	file_server_mux_mux_error_proto_rawDesc = nil
	file_server_mux_mux_error_proto_goTypes = nil
	file_server_mux_mux_error_proto_depIdxs = nil
}
